export const fa = {
   app: {
      fallbackWorkspace: 'تسکارا',
      loading: 'در حال بارگذاری...',
      unknown: 'نامشخص',
      unset: 'تعیین نشده',
      noDate: 'بدون تاریخ',
      empty: 'موردی برای نمایش وجود ندارد.',
      save: 'ثبت',
      cancel: 'لغو',
      close: 'بستن',
      more: 'بیشتر',
      search: 'جستجو',
      create: 'ایجاد',
      confirm: 'تایید',
      smsConfirmDescription: 'از ارسال پیامک مطمئن هستید؟',
   },
   nav: {
      inbox: 'صندوق ورودی',
      announcements: 'اطلاعیه‌ها',
      meetings: 'جلسه‌ها',
      allTasks: 'همه کارها',
      myIssues: 'کارهای من',
      workspace: 'فضای کاری',
      projects: 'پروژه‌ها',
      views: 'نماها',
      more: 'بیشتر',
      teams: 'تیم‌ها',
      issues: 'کارها',
      leaderboard: 'لیدربورد',
      heartbeat: 'نبض تیم‌ها',
      members: 'اعضا',
      settings: 'تنظیمات',
      cycles: 'چرخه‌ها',
      try: 'امکانات',
      recentActivity: 'آخرین تغییرات',
      createIssue: 'ایجاد کار',
      commandMenu: 'منوی فرمان',
      keyboardShortcuts: 'میانبرهای صفحه‌کلید',
   },
   pages: {
      inboxDescription: 'اعلان‌های مرتبط با کارهای تسکارا و آخرین رویدادهای فضای کاری.',
      announcementsDescription: 'اطلاعیه‌های سازمانی، مخاطبان، وضعیت خواندن و ارسال دستی پیامک.',
      meetingsDescription: 'جلسه‌ها، صورت‌جلسه‌ها، شرکت‌کننده‌ها و تبدیل خروجی جلسه به کارهای قابل پیگیری.',
      allTasksDescription: 'نمای همه کارها در تمام تیم‌ها و پروژه‌های فضای کاری.',
      membersDescription: 'نمای کاربران، نقش‌ها، اتصال مترموست و حجم کار جاری.',
      leaderboardDescription: 'جدول رقابتی عملکرد کارکنان بر اساس تعداد کارهای انجام‌شده.',
      projectsDescription: 'فهرست پروژه‌ها با ساختار و رفتار نزدیک به لینیر.',
      heartbeatDescription: 'نمای زنده از وضعیت کارها، پیشرفت، ریسک‌ها و به‌روزرسانی‌های همه تیم‌ها.',
      settingsDescription: 'مدیریت فضای کاری، ساخت کاربران جدید، و کنترل نقش‌ها از همین صفحه.',
      issuesDescription: 'نمای اصلی کارها با گروه‌بندی وضعیت، جزئیات کناری، و میانبرهای سبک لینیر.',
      teamsDescription: 'ساخت و مرور تیم‌های داخلی برای سازمان‌دهی پروژه‌ها و اعضا.',
   },
   status: {
      BACKLOG: 'بک‌لاگ',
      TODO: 'برای انجام',
      IN_PROGRESS: 'در حال انجام',
      IN_REVIEW: 'در بازبینی',
      BLOCKED: 'مسدود',
      DONE: 'انجام‌شده',
      CANCELED: 'لغوشده',
   },
   priority: {
      NO_PRIORITY: 'بدون اولویت',
      LOW: 'کم',
      MEDIUM: 'متوسط',
      HIGH: 'زیاد',
      URGENT: 'فوری',
   },
   projectStatus: {
      ACTIVE: 'فعال',
      PAUSED: 'متوقف',
      COMPLETED: 'تکمیل‌شده',
      ARCHIVED: 'آرشیوشده',
   },
   role: {
      OWNER: 'مالک',
      ADMIN: 'مدیر',
      MEMBER: 'عضو',
      GUEST: 'مهمان',
      AGENT: 'عامل',
   },
   settings: {
      workspace: 'فضای کاری',
      workspaceOverview: 'نمای کلی فضای کاری و کاربر فعلی.',
      currentUser: 'کاربر فعلی',
      unreadNotifications: 'اعلان خوانده‌نشده',
      createUser: 'ایجاد کاربر',
      createUserDescription: 'کاربر را بسازید و مستقیم به فضای کاری اضافه کنید.',
      name: 'نام',
      email: 'ایمیل',
      phone: 'شماره موبایل',
      mattermostUsername: 'نام کاربری مترموست',
      role: 'نقش',
      creating: 'در حال ثبت...',
      accessManagement: 'مدیریت دسترسی',
      accessDescription: 'نقش کاربران را تغییر دهید. API از حذف آخرین مالک جلوگیری می‌کند.',
      noUsers: 'کاربری برای مدیریت وجود ندارد.',
      loadFailed: 'بارگذاری تنظیمات ناموفق بود.',
      createFailed: 'ایجاد کاربر ناموفق بود.',
      roleUpdateFailed: 'به‌روزرسانی نقش ناموفق بود.',
   },
   heartbeat: {
      active: 'فعال',
      activeAssignedTasks: 'کار فعال',
      activeNow: 'فعال اکنون',
      activePastDue: 'فعال و گذشته از موعد',
      allTeams: 'همه تیم‌ها',
      allTime: 'همه زمان‌ها',
      atRisk: 'نیازمند توجه',
      blockedNow: 'مسدود اکنون',
      blockedOverdueStale: 'مسدود، دیرکرد یا بی‌حرکت',
      blockedShare: 'سهم انسداد',
      changedTasks: 'کارهای تغییرکرده',
      done: 'انجام‌شده',
      doneInWindow: 'انجام‌شده',
      doneShare: 'سهم انجام‌شده',
      doneTasks: 'انجام‌شده اخیر',
      empty: 'هنوز کاری برای ساخت نبض تیم‌ها وجود ندارد.',
      inProgress: 'در جریان',
      inProgressTasks: 'در حال انجام',
      last: 'آخرین',
      latest: 'آخرین تغییر',
      needsAttention: 'نیازمند توجه',
      noDone: 'در این بازه کاری انجام نشده است.',
      noIdlePeople: 'شخصی بدون کار در حال انجام وجود ندارد.',
      noInProgress: 'کاری در جریان نیست.',
      noActiveAssignedTasks: 'بدون کار فعال',
      noOverdue: 'کاری از موعد گذشته نیست.',
      noRecentUpdates: 'در این بازه تغییری ثبت نشده است.',
      noRisks: 'ریسک فعالی دیده نمی‌شود.',
      noTeamData: 'داده‌ای برای این تیم‌ها وجود ندارد.',
      onTrack: 'روان',
      overdue: 'گذشته از موعد',
      overdueNow: 'دیرکرد',
      quiet: 'کم‌تحرک',
      recentUpdates: 'آخرین به‌روزرسانی‌ها',
      refresh: 'به‌روزرسانی',
      risks: 'ریسک‌ها',
      stale: 'بی‌حرکت',
      startedOrReview: 'شروع‌شده یا در بازبینی',
      statusFlow: 'جریان وضعیت‌ها',
      statusFlowCaption: 'توزیع کارها در بک‌لاگ، در حال انجام، بازبینی، انسداد، انجام‌شده و لغوشده.',
      tasks: 'کار',
      teamHealth: 'سلامت تیم‌ها',
      teamFilter: 'فیلتر تیم',
      teams: 'تیم‌ها',
      unassignedTeam: 'بدون تیم',
      updated: 'به‌روزشده',
      updatedInWindow: 'به‌روزشده',
      watch: 'قابل پیگیری',
      workInSystem: 'بک‌لاگ، انجام‌دادنی، در جریان و مسدود',
      withoutInProgress: 'بدون کار در حال انجام',
   },
   issue: {
      all: 'همه کارها',
      active: 'فعال',
      backlog: 'بک‌لاگ',
      filters: 'فیلترها',
      display: 'نمایش',
      saveView: 'ذخیره نما',
      saveAsNewView: 'ذخیره به‌عنوان نمای جدید',
      updateView: 'به‌روزرسانی نما',
      deleteView: 'حذف نما',
      viewName: 'نام نما',
      sharedView: 'نمای مشترک',
      noSavedViews: 'هنوز نمای ذخیره‌شده‌ای وجود ندارد.',
      listView: 'فهرست',
      boardView: 'بورد',
      grouping: 'گروه‌بندی',
      ordering: 'مرتب‌سازی',
      showEmptyGroups: 'نمایش گروه‌های خالی',
      noGroupingValue: 'بدون مقدار',
      searchPlaceholder: 'جستجو در کارها...',
      noMatchingIssues: 'کاری مطابق این فیلترها پیدا نشد.',
      newIssue: 'کار جدید',
      titlePlaceholder: 'عنوان کار',
      descriptionPlaceholder: 'توضیح اضافه کنید...',
      status: 'وضعیت',
      priority: 'اولویت',
      weight: 'وزن',
      assignee: 'مسئول',
      project: 'پروژه',
      labels: 'برچسب‌ها',
      labelsPlaceholder: 'برچسب‌ها را با ویرگول جدا کنید',
      dueAt: 'سررسید',
      dueAtPlaceholder: 'انتخاب سررسید',
      clearDueAt: 'حذف تاریخ سررسید',
      createMore: 'ادامه ساخت',
      createIssue: 'ایجاد کار',
      createFullscreen: 'نمای تمام‌صفحه',
      updateFailed: 'به‌روزرسانی کار ناموفق بود.',
      createFailed: 'ایجاد کار ناموفق بود.',
      deleteFailed: 'حذف کار ناموفق بود.',
      loadFailed: 'بارگذاری کارها ناموفق بود.',
      created: 'کار ایجاد شد.',
      createdOffline: 'کار ایجاد شد و پس از اتصال همگام‌سازی می‌شود.',
      deleted: 'کار حذف شد.',
      deleteConfirm: 'این کار حذف شود؟',
      pendingSync: 'در انتظار همگام‌سازی',
      pendingAttachmentUpload: 'کار به‌صورت آفلاین ساخته شد. پس از همگام‌سازی، فایل‌ها را دوباره پیوست کنید.',
      titleRequired: 'عنوان کار الزامی است.',
      invalidWeight: 'وزن کار باید فقط یکی از مقادیر ۱، ۲، ۳، ۴ یا ۸ باشد.',
      projectRequired: 'برای ایجاد کار، ابتدا یک پروژه بسازید.',
      invalidDate: 'فرمت تاریخ جلالی نامعتبر است. از الگوی ۱۴۰۵/۰۲/۰۴ ۱۴:۳۰ استفاده کنید.',
      noIssuesInGroup: 'کاری در این گروه وجود ندارد.',
      noIssueSelected: 'یک کار را برای مشاهده جزئیات انتخاب کنید.',
      properties: 'ویژگی‌ها',
      activity: 'فعالیت',
      comments: 'نظرها',
      attachments: 'پیوست‌ها',
      uploadAttachment: 'افزودن پیوست',
      attachToDescription: 'افزودن سند به توضیح',
      attachToComment: 'افزودن سند به دیدگاه',
      dropAttachments: 'فایل‌ها را برای پیوست رها کنید',
      removeAttachment: 'حذف پیوست',
      attachmentUploadFailed: 'بارگذاری پیوست ناموفق بود.',
      attachmentUploaded: 'پیوست اضافه شد.',
      attachmentsUploaded: '{count} پیوست اضافه شد.',
      noActivity: 'فعالیتی برای این کار ثبت نشده است.',
      commentFailed: 'ثبت دیدگاه ناموفق بود.',
      commentCreated: 'دیدگاه ثبت شد.',
      moreActions: 'اقدام‌های بیشتر',
      sendTaskSms: 'ارسال پیامک کار',
      sendTaskFollowUpSms: 'ارسال پیامک پیگیری کار',
      smsSent: 'پیامک کار ارسال شد.',
      smsFollowUpSent: 'پیامک پیگیری کار ارسال شد.',
      smsFailed: 'ارسال پیامک ناموفق بود.',
      smsNoAssignee: 'این کار مسئول ندارد.',
      smsNoPhone: 'شماره موبایل مسئول ثبت نشده است.',
      subtasks: 'زیرکارها',
      dependencies: 'وابستگی‌ها',
      addSubIssues: 'افزودن زیرکار',
      leaveComment: 'دیدگاه بنویسید...',
      details: 'جزئیات کار',
      createdAt: 'زمان ایجاد',
      updatedAt: 'آخرین تغییر',
      currentUser: 'کاربر فعلی',
      noAssignee: 'بدون مسئول',
   },
   announcement: {
      title: 'اطلاعیه‌ها',
      newAnnouncement: 'اطلاعیه جدید',
      titlePlaceholder: 'عنوان اطلاعیه',
      bodyPlaceholder: 'متن اطلاعیه را بنویسید...',
      recipients: 'مخاطبان',
      draft: 'پیش‌نویس',
      published: 'منتشرشده',
      archived: 'آرشیوشده',
      create: 'ایجاد اطلاعیه',
      saveDraft: 'ذخیره پیش‌نویس',
      publish: 'انتشار',
      publishDraft: 'انتشار پیش‌نویس',
      publishDraftHint: 'برای انتشار، مخاطبان را انتخاب کنید. بعد از انتشار، اطلاعیه در صندوق ورودی مخاطبان قرار می‌گیرد.',
      publishDraftNoRecipients: 'برای انتشار حداقل یک مخاطب لازم است.',
      publishedToast: 'اطلاعیه منتشر شد.',
      markRead: 'خواندم',
      read: 'خوانده شده',
      sendSms: 'ارسال پیامک اطلاعیه',
      smsSent: 'پیامک اطلاعیه ارسال شد.',
      smsSummary: 'ارسال‌شده: {sent}، بدون شماره: {skipped}، ناموفق: {failed}',
      loadFailed: 'بارگذاری اطلاعیه‌ها ناموفق بود.',
      createFailed: 'ایجاد اطلاعیه ناموفق بود.',
      updateFailed: 'به‌روزرسانی اطلاعیه ناموفق بود.',
      smsFailed: 'ارسال پیامک اطلاعیه ناموفق بود.',
      noAnnouncements: 'اطلاعیه‌ای برای نمایش وجود ندارد.',
      selectAnnouncement: 'یک اطلاعیه را انتخاب کنید.',
      unread: 'خوانده‌نشده',
   },
   meeting: {
      title: 'جلسه‌ها',
      newMeeting: 'جلسه جدید',
      titlePlaceholder: 'عنوان جلسه',
      descriptionPlaceholder: 'دستور جلسه یا صورت‌جلسه را بنویسید...',
      participants: 'شرکت‌کننده‌ها',
      owner: 'مسئول جلسه',
      project: 'پروژه',
      team: 'تیم',
      scheduledAt: 'زمان جلسه',
      status: 'وضعیت',
      planned: 'برنامه‌ریزی‌شده',
      held: 'برگزارشده',
      canceled: 'لغوشده',
      archived: 'آرشیوشده',
      create: 'ایجاد جلسه',
      createTasks: 'ساخت کار از جلسه',
      actionItems: 'کارهای خروجی',
      actionTitlePlaceholder: 'عنوان کار خروجی',
      sendSms: 'ارسال پیامک جلسه',
      smsSent: 'پیامک جلسه ارسال شد.',
      smsSummary: 'ارسال‌شده: {sent}، بدون شماره: {skipped}، ناموفق: {failed}',
      loadFailed: 'بارگذاری جلسه‌ها ناموفق بود.',
      createFailed: 'ایجاد جلسه ناموفق بود.',
      updateFailed: 'به‌روزرسانی جلسه ناموفق بود.',
      taskCreateFailed: 'ساخت کارهای جلسه ناموفق بود.',
      smsFailed: 'ارسال پیامک جلسه ناموفق بود.',
      noMeetings: 'جلسه‌ای برای نمایش وجود ندارد.',
      selectMeeting: 'یک جلسه را انتخاب کنید.',
   },
   project: {
      all: 'همه پروژه‌ها',
      active: 'فعال',
      newProject: 'پروژه جدید',
      unassignedProjects: 'پروژه‌های بدون تیم',
      addToTeam: 'افزودن به تیم',
      teamUpdated: 'تیم پروژه به‌روزرسانی شد.',
      teamUpdateFailed: 'به‌روزرسانی تیم پروژه ناموفق بود.',
      namePlaceholder: 'نام پروژه',
      summaryPlaceholder: 'خلاصه کوتاه اضافه کنید...',
      descriptionPlaceholder: 'توضیح، طرح پروژه، یا ایده‌ها را بنویسید...',
      keyPrefix: 'کلید پروژه',
      keyPrefixPlaceholder: 'CORE',
      status: 'وضعیت',
      lead: 'مسئول پروژه',
      team: 'تیم',
      members: 'اعضا',
      start: 'شروع',
      target: 'هدف',
      labels: 'برچسب‌ها',
      dependencies: 'وابستگی‌ها',
      milestones: 'مایلستون‌ها',
      createProject: 'ایجاد پروژه',
      createFailed: 'ایجاد پروژه ناموفق بود.',
      loadFailed: 'بارگذاری پروژه‌ها ناموفق بود.',
      created: 'پروژه ایجاد شد.',
      nameRequired: 'نام و کلید پروژه الزامی است.',
      list: 'فهرست پروژه‌ها',
      issueCount: 'تعداد کار',
      noProjects: 'هنوز پروژه‌ای ثبت نشده است.',
   },
   inbox: {
      notifications: 'اعلان‌ها',
      unread: 'خوانده‌نشده',
      markAllRead: 'خواندن همه',
      markRead: 'علامت‌گذاری به عنوان خوانده‌شده',
      noNotifications: 'اعلانی برای کارهای دنبال‌شده، واگذاری‌ها یا منشن‌های شما وجود ندارد.',
      noDescription: 'این اعلان توضیح تکمیلی ندارد.',
      selectNotification: 'یک اعلان را برای مشاهده جزئیات انتخاب کنید.',
      loadFailed: 'بارگذاری صندوق ورودی ناموفق بود.',
      markAllFailed: 'علامت‌گذاری همه اعلان‌ها ناموفق بود.',
      registeredAt: 'زمان ثبت',
      type: 'نوع اعلان',
   },
   command: {
      title: 'منوی فرمان',
      description: 'مسیرها و عملیات تسکارا را اجرا کنید.',
      createIssue: 'ایجاد کار',
      createIssueDescription: 'باز کردن فرم ساخت کار',
      createProject: 'ایجاد پروژه',
      createProjectDescription: 'باز کردن فرم ساخت پروژه',
      goAllTasks: 'رفتن به همه کارها',
      goIssues: 'رفتن به کارها',
      goInbox: 'رفتن به صندوق ورودی',
      goProjects: 'رفتن به پروژه‌ها',
      goLeaderboard: 'رفتن به لیدربورد',
      goHeartbeat: 'رفتن به نبض تیم‌ها',
      goMembers: 'رفتن به اعضا',
      goTeams: 'رفتن به تیم‌ها',
      goSettings: 'رفتن به تنظیمات',
   },
   shortcuts: {
      title: 'میانبرهای صفحه‌کلید',
      description: 'میانبرهای سبک لینیر برای رابط راست‌به‌چپ تسکارا.',
      openCommandMenu: 'باز کردن منوی فرمان',
      createIssue: 'ایجاد کار',
      createIssueFullscreen: 'ایجاد کار در نمای تمام‌صفحه',
      toggleDetails: 'نمایش یا پنهان کردن جزئیات',
      moveRow: 'جابجایی بین ردیف‌ها',
      selectRow: 'انتخاب ردیف فعال',
      close: 'بستن یا پاک کردن انتخاب',
      openHelp: 'نمایش راهنمای میانبرها',
   },
   leaderboard: {
      topEmployeeBadge: 'کارمندان نمونه',
      loadFailed: 'بارگذاری لیدربورد ناموفق بود.',
      timeFilter: 'بازه زمانی',
      daily: 'روزانه',
      weekly: 'هفتگی',
      monthly: 'ماهانه',
      yearly: 'سالانه',
      yearlyDisabled: '(غیرفعال)',
   },
   table: {
      rank: 'رتبه',
      user: 'کاربر',
      role: 'نقش',
      phone: 'موبایل',
      mattermost: 'مترموست',
      joinedAt: 'عضویت از',
      changeRole: 'تغییر نقش',
      assigned: 'سپرده‌شده',
      done: 'انجام‌شده',
      speed: 'عملکرد',
      reported: 'گزارش‌شده',
      team: 'تیم',
      slug: 'شناسه',
      projects: 'پروژه‌ها',
      members: 'اعضا',
   },
} as const;
